# Dockerfile para order_service
FROM python:3.10-slim

WORKDIR /app

COPY order_service/ /app/
COPY requirements.txt /app/

RUN pip install --upgrade pip && pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org -r /app/requirements.txt

# Variáveis de ambiente para Django
ENV DJANGO_SETTINGS_MODULE=order_service.settings

# Comando para executar o script que gerencia Django + Consumer
CMD ["python", "start_services.py"]
