# Generated by Django 5.2.3 on 2025-07-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.CharField(db_column='Menu Item Name', max_length=124)),
                ('quantity', models.IntegerField(db_column='Quantity')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Oders',
            },
        ),
    ]
