# Generated by Django 5.2.3 on 2025-07-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_id',
            field=models.IntegerField(db_column='Client ID', default=1),
            preserve_default=False,
        ),
    ]
